Repository halo-sigs/plugin-photos, pull requests merged in 2024-07, with the labels that each got.

#46 chore: remove deprecated plugin wrapper
  build.gradle
  src/main/java/run/halo/photos/PhotoPlugin.java
  src/main/resources/plugin.yaml
Labels: lgtm, release-note-none, approved

#47 chore: update workflows config
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  .github/workflows/workflow.yaml
  build.gradle
Labels: lgtm, release-note-none, approved

#48 chore: remove unnecessary class
  build.gradle
  src/main/java/run/halo/photos/CustomEndpointsBuilder.java
  src/main/java/run/halo/photos/PhotoConfiguration.java
  src/main/java/run/halo/photos/PhotoGroupEndpoint.java
  src/main/resources/plugin.yaml
Labels: lgtm, release-note-none, approved

#50 refactor: replace tailwindcss with unocss
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  build.gradle
  console/.eslintrc.cjs
  console/env.d.ts
  console/package.json
  console/pnpm-lock.yaml
  console/postcss.config.js
  console/prettier.config.cjs
  console/prettier.config.js
  console/src/components/GroupEditingModal.vue
  console/src/components/GroupList.vue
  console/src/components/LazyImage.vue
  console/src/components/PhotoEditingModal.vue
  console/src/index.ts
  console/src/styles/tailwind.css
  console/src/views/PhotoList.vue
  console/tailwind.config.js
  console/uno.config.ts
  console/vite.config.ts
Labels: lgtm, kind/improvement, release-note-none, approved

#51 refactor: use globally provided axios instance
  console/env.d.ts
  console/package.json
  console/pnpm-lock.yaml
  console/src/components/GroupEditingModal.vue
  console/src/components/GroupList.vue
  console/src/components/PhotoEditingModal.vue
  console/src/utils/api-client.ts
  console/src/utils/date.ts
  console/src/views/PhotoList.vue
Labels: lgtm, kind/improvement, release-note, approved
