Repository halo-sigs/plugin-photos, pull requests merged in 2025-05, with the labels that each got.

#62 Adapt Halo 2.21
  src/main/java/run/halo/photos/PhotoEndpoint.java
  src/main/java/run/halo/photos/PhotoGroupEndpoint.java
  src/main/java/run/halo/photos/PhotoPlugin.java
  src/main/java/run/halo/photos/PhotoQuery.java
  src/main/java/run/halo/photos/finders/impl/PhotoFInderImpl.java
  src/main/java/run/halo/photos/service/impl/PhotoGroupServiceImpl.java
  src/main/java/run/halo/photos/service/impl/PhotoServiceImpl.java
Labels: lgtm, release-note, approved

#63 fix: resolve ui build dist location issue
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  console/.env
  console/package.json
  console/pnpm-workspace.yaml
Labels: lgtm, release-note-none, approved

#64 Bump Gradle to 8.14 and Lombok plugin to 8.13.1
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: release-note-none
